version: '3'
services:
  carbtographer:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - 9001:9001

  nats:
    image: nats-streaming:0.11.2
    restart: on-failure