version: '3'
services:
  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    ports:
        - "9001:9001" # API port
    environment:
        PORT: '9001'
    env_file: 
      - .env
