version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
        - "6379:6379"
  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    ports:
        - "9001:9001"
    depends_on:
        - postgres
        - redis
    environment:
        PORT: '9001'
    env_file: 
      - .env

